### ISSUE TITLE
Spotify Mixin throws exception on auth call back

### ISSUE THREAD

**Issue by peymanmortazavi** [QuantifiedSelfless/quantifiedSelf#3]
Here is the output

[E 151001 11:12:29 web:1496] Uncaught exception GET /auth/spotify?code=AQC9tHbiqpP57fivqFCtZAzw41U1p1nLSKvhIrHsA4IFcALBMlT0yJjcfeQ1rrE0jJktTWkrroSOABqr-Yy1rNUS_EgrGRMV5N71jiECiwgfJ6_H-rXxe6hlohyLZDLP_PTm4XYKQ47YDjlLURrIdN-bG6fJEaNok3Vu_ZRB78WWan_roD_dgQMG7gjAsSh4zOwkcSL04_-xWlT5gm72pwMH9IHfhnvUL8PZFKYvODqvREUl4kjhJfRk3EDDgW5jWrx-g8VqBB8LTILcAVVm1oMVCO6Lf4rD4jEkcpO_ha_Bb6JHwyBL_mJSqpQx5BRREbGf7XQJkWofDrronF6gPQSyAnpOWpfFJUyDh_9JdQBVdUv9NY6w (::1)
    HTTPServerRequest(protocol='https', host='localhost:6060', method='GET', uri='/auth/spotify?code=AQC9tHbiqpP57fivqFCtZAzw41U1p1nLSKvhIrHsA4IFcALBMlT0yJjcfeQ1rrE0jJktTWkrroSOABqr-Yy1rNUS_EgrGRMV5N71jiECiwgfJ6_H-rXxe6hlohyLZDLP_PTm4XYKQ47YDjlLURrIdN-bG6fJEaNok3Vu_ZRB78WWan_roD_dgQMG7gjAsSh4zOwkcSL04_-xWlT5gm72pwMH9IHfhnvUL8PZFKYvODqvREUl4kjhJfRk3EDDgW5jWrx-g8VqBB8LTILcAVVm1oMVCO6Lf4rD4jEkcpO_ha_Bb6JHwyBL_mJSqpQx5BRREbGf7XQJkWofDrronF6gPQSyAnpOWpfFJUyDh_9JdQBVdUv9NY6w', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:6060', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:6060/signup', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1369, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(_args, *_kwargs)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1581, in future_complete
        f.result()
      File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Library/Python/2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/peyman/Projects/quantifiedSelf/app/spotify_auth.py", line 22, in get
        code=self.get_argument('code'))
      File "/Library/Python/2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Library/Python/2.7/site-packages/tornado/auth.py", line 140, in wrapper
        f(_args, **kwargs)
      File "/Users/peyman/Projects/quantifiedSelf/app/spotifyMix.py", line 27, in get_authenticated_user
        http = self.get_auth_http_client()
    AttributeError: 'SpotifyAuth' object has no attribute 'get_auth_http_client'
[E 151001 11:12:29 web:1908] 500 GET /auth/spotify?code=AQC9tHbiqpP57fivqFCtZAzw41U1p1nLSKvhIrHsA4IFcALBMlT0yJjcfeQ1rrE0jJktTWkrroSOABqr-Yy1rNUS_EgrGRMV5N71jiECiwgfJ6_H-rXxe6hlohyLZDLP_PTm4XYKQ47YDjlLURrIdN-bG6fJEaNok3Vu_ZRB78WWan_roD_dgQMG7gjAsSh4zOwkcSL04_-xWlT5gm72pwMH9IHfhnvUL8PZFKYvODqvREUl4kjhJfRk3EDDgW5jWrx-g8VqBB8LTILcAVVm1oMVCO6Lf4rD4jEkcpO_ha_Bb6JHwyBL_mJSqpQx5BRREbGf7XQJkWofDrronF6gPQSyAnpOWpfFJUyDh_9JdQBVdUv9NY6w (::1) 2.90ms

**Comment by wannabeCitizen** [comment]
just push to develop branch the fix for this
