### ISSUE TITLE
Twitter Auth can't find cookie

### ISSUE THREAD

**Issue by wannabeCitizen** [QuantifiedSelfless/quantifiedSelf#68]
When running on production, after a user finalizes their auth decision via Twitter, the redirect to our server throws a 500 error. This ONLY happens with the Twitter Auth! The error is:

```
Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1613, in future_complete
        f.result()
      File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/web/quantifiedSelf/lib/basehandler.py", line 93, in get
        user_id = self.get_secure_cookie("user_id", None)
      File "/web/quantifiedSelf/lib/basehandler.py", line 79, in get_secure_cookie
        return result.decode()
    AttributeError: 'NoneType' object has no attribute 'decode'
```

We have already verified that the 'Cookie' Header is indeed being sent just like on every other request. It doesn't make sense why in this one case `get_secure_cookie` fails. @mynameisfiber any help would be amazing. We've banged our head on this and everything (including the environment that the request has during processing) says the cookie should be there. Why would this / could this fail in this lone context?

**Comment by wannabeCitizen** [comment]
Update on this:
The user_id cookie is missing, but I have no idea how only with Twitter.

Normally a request comes in with the following cookies:
`['auth-result', 'G_ENABLED_IDPS', 'user_id']`

When the Twitter auth redirect happens, we only have:
`['G_ENABLED_IDPS']`

**Comment by wannabeCitizen** [comment]
Removed `www` from the twitter redirect URI and it somehow fixed the cookie resetting issue!
